import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Vertical from "@/components/Verticalnav";
import Horizontal from "@/components/Horizontalnav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col lg:flex-row">
          <div className="hidden lg:flex">
            <Vertical />
          </div>

          <div className="lg:hidden flex ">
            <Horizontal />
          </div>

          <div className="lg:ml-[230px]">{children}</div>
        </div>
      </body>
    </html>
  );
}
